server:
  port: 8080

spring:
  application:
    name: quizora-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/quizora
    username: postgres
    password: basket1402
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Hibernate vérifie, Flyway crée
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
flyway:
  enabled: true
  baseline-on-migrate: true
